insert into todo (id,username,description,target_date,done)
values (10001,'yatin','Get AWS Certified',CURRENT_DATE(),false);
insert into todo (id,username,description,target_date,done)
values (10002,'yatin','Get GCP Certified',CURRENT_DATE(),false);
insert into todo (id,username,description,target_date,done)
values (10003,'yatin','Get SEC+ Certified',CURRENT_DATE(),false);
insert into todo (id,username,description,target_date,done)
values (10004,'yatin','Get CEH Certified',CURRENT_DATE(),false);
insert into todo (id,username,description,target_date,done)
values (10005,'yatin','Get OSCP Certified',CURRENT_DATE(),false);
